version: '3'
services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: telegram-bot
    ports:
      - "3050:3000"
    # networks:
    #   nginx_nginx-proxy-manager:
  telegram-chat:
    build:
      context: .
      dockerfile: chatDockerfile
    restart: unless-stopped
    container_name: telegram-chat
    ports:
      - "3000:3000"
#     networks:
#       nginx_nginx-proxy-manager:
# networks:
#   nginx_nginx-proxy-manager:
#     external: true