version: '3'
services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    restart: unless-stopped
    container_name: telegram-bot
    ports:
      - "3000:3000"
    networks:
      nginx_nginx-proxy-manager:
networks:
  nginx_nginx-proxy-manager:
    external: true