version: '3'
services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    ports:
      - "3000:3000"
    networks:
      nginx_nginx-proxy-manager:
networks:
  nginx_nginx-proxy-manager:
    external: true