version: '3'
services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    ports:
      - "8081:8081"
    networks:
      nginx_nginx-proxy-manager:
networks:
  nginx_nginx-proxy-manager:
    external: true