version: '3'
services:
  telegram_api:
    image: api.registry.viomitra.ru/telegram_api:latest
    ports:
      - 3000:3050
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      labels:
        - traefik.enable=false
  telegram_chat:
    image: api.registry.viomitra.ru/telegram_chat:latest
    restart: unless-stopped
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.telegram_chat-http.rule=Host(`bot.viomitra.ru`)
        - traefik.http.routers.telegram_chat-http.entrypoints=http
        - traefik.http.routers.telegram_chat-http.middlewares=https-redirect
        - traefik.http.routers.telegram_chat-https.rule=Host(`bot.viomitra.ru`)
        - traefik.http.routers.telegram_chat-https.entrypoints=https
        - traefik.http.routers.telegram_chat-https.tls=true
        - traefik.http.routers.telegram_chat-https.tls.certresolver=le
        - traefik.http.services.telegram_chat.loadbalancer.server.port=3000
networks:
  traefik-public:
    external: true
